parameters:
#    openview_export.example.class: Openview\ExportBundle\Example

services:
#    openview_export.example:
#        class: %openview_export.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
